## DATA 111 Midterm 1

# 1

In [1]:
from datascience import *
import numpy as np
import math
import matplotlib.pyplot as plt

/Users/kamilalarripa/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/kamilalarripa/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
make_array('heads', 'tails', 'tails', 'tails') == 'tails'

array([False,  True,  True,  True], dtype=bool)

In [3]:
make_array(2 , 3, 4)**2 - make_array(1, 1, 1)

array([ 3,  8, 15])

In [4]:
'I <' + str(round(math.pi)) + 'data science!'

'I <3data science!'

In [5]:
sum(make_array(1, 3, 4, 1) != 3)

3

In [6]:
val = 3
for j in make_array(1, 3, 2):
    val = val ** j - 1
print(val)    

48


# 2 - choose d

In [7]:
def find_indices(data, target):
    data_table = Table().with_columns('indices', np.arange(len(data)), 'values', data)
    return data_table.where('values', target).column('indices')

In [8]:
find_indices(make_array(5, 8, 10, 8, 3, 8), 8)

array([1, 3, 5])

# 2 a (incorrect)
The problem is `data` is an array, and `.where` is a table method, so this creates an error.

In [9]:
def find_indices(data, target):
    return data.where('values', target)
find_indices(make_array(5, 8, 10, 8, 3, 8), 8)

AttributeError: 'numpy.ndarray' object has no attribute 'where'

# 2 b (incorrect)
This appends the matching values `i` instead of their indices.

In [10]:
def find_indices(data, target):
    indices = make_array()
    for i in data:
        if i == target:
            indices = np.append(indices, i)
    return indices
find_indices(make_array(5, 8, 10, 8, 3, 8), 8)

array([ 8.,  8.,  8.])

# 2 c (incorrect)
This iterates over the positions correctly, but still appends the value (`data.item(i)`), not the index.

In [11]:
def find_indices(data, target):
    indices = make_array()
    for i in np.arange(len(data)):
        if data.item(i) == target:
            indices = np.append(indices, data.item(i))
    return indices
find_indices(make_array(5, 8, 10, 8, 3, 8), 8)

array([ 8.,  8.,  8.])

# 3

In [12]:
x = 5
if x < 5:
    x = x + 2
elif x == 5:
    x= 2 * x
else:
    x = x-2
print("x is", x)    

x is 10


# 4

In [13]:
suspects = Table().with_columns(
    'Name',   make_array('John','Alice','Bob','Eve','David'  # ... add others
    ),
    'Alibi',  make_array('I was at the scene','I was at home','I was with friends','I was at the scene','I was sleeping'  # ...
    ),
    'Motive', make_array('revenge','jealousy','financial gain','revenge','unknown'  # ...
    ),
    'Distance', make_array(5,10,12,23,0  # ... use the provided numbers
    )
)
suspects

Name,Alibi,Motive,Distance
John,I was at the scene,revenge,5
Alice,I was at home,jealousy,10
Bob,I was with friends,financial gain,12
Eve,I was at the scene,revenge,23
David,I was sleeping,unknown,0


# 4 a

In [14]:
nearby = suspects.where("Distance", are.below(10))
nearby

Name,Alibi,Motive,Distance
John,I was at the scene,revenge,5
David,I was sleeping,unknown,0


# 4 b

In [15]:
sus_alibi = nearby.where('Alibi', "I was at the scene")
sus_alibi


Name,Alibi,Motive,Distance
John,I was at the scene,revenge,5


# 4 c

In [16]:
sus_motive = sus_alibi.where('Motive', 'revenge')
sus_motive

Name,Alibi,Motive,Distance
John,I was at the scene,revenge,5


# 4 d

In [17]:
sus_motive.num_rows


1

# 5

In [18]:
enso = Table().with_columns(
    'Date', make_array('1/1/1950', '2/1/1950', '3/1/1950', '4/1/1950', '5/1/1950', '6/1/1950', '1/1/1960'),
    'Year', make_array(1950, 1950, 1950, 1950, 1950, 1950, 1960),
    'Month', make_array('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JAN'),
    'Global Temperature Anomalies', make_array(-0.2, -0.26, -0.08, -0.16, -0.02, -0.01, -.02)
)
enso

Date,Year,Month,Global Temperature Anomalies
1/1/1950,1950,JAN,-0.2
2/1/1950,1950,FEB,-0.26
3/1/1950,1950,MAR,-0.08
4/1/1950,1950,APR,-0.16
5/1/1950,1950,MAY,-0.02
6/1/1950,1950,JUN,-0.01
1/1/1960,1960,JAN,-0.02


# 5 a


In [19]:
enso_yearly = (
    enso.select('Year', 'Global Temperature Anomalies')
        .group('Year', np.average)
)
enso_yearly


Year,Global Temperature Anomalies average
1950,-0.121667
1960,-0.02


# 5 b

In [20]:
enso_yearly.plot('Year','Global Temperature Anomalies average')

In [21]:
# here is an example from documentation
table = Table().with_columns(
    'days',  make_array(0, 1, 2, 3, 4, 5),
    'price', make_array(90.5, 90.00, 83.00, 95.50, 82.00, 82.00),
    'projection', make_array(90.75, 82.00, 82.50, 82.50, 83.00, 82.50))
table.plot('days', 'price') 

# 6

In [22]:
# humboldt_customers table
humboldt_customers = Table().with_columns(
    'Customer_ID',   make_array(1, 2, 3, 4, 5),
    'Customer_Name', make_array('Alice', 'Bob', 'Charlie', 'David', 'Eve'),
    'City',          make_array('Arcata', 'Arcata', 'Eureka', 'Trinidad', 'Eureka')
)

# humboldt_sales table
humboldt_sales = Table().with_columns(
    'Product',         make_array('A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A'),
    'Items sold',      make_array(10, 10, 15, 12, 9, 16, 9, 11, 14, 11),
    'Sale amount ($)', make_array(100, 200, 150, 120, 180, 160, 90, 220, 140, 110),
    'Customer_ID',     make_array(1, 2, 3, 4, 1, 2, 5, 4, 3, 5)
)

In [23]:
humboldt_customers

Customer_ID,Customer_Name,City
1,Alice,Arcata
2,Bob,Arcata
3,Charlie,Eureka
4,David,Trinidad
5,Eve,Eureka


In [24]:
humboldt_sales

Product,Items sold,Sale amount ($),Customer_ID
A,10,100,1
B,10,200,2
C,15,150,3
A,12,120,4
B,9,180,1
C,16,160,2
A,9,90,5
B,11,220,4
C,14,140,3
A,11,110,5


# 6 a choice 3

In [25]:
 (humboldt_sales.select('Product','Items sold')
                .group('Product', sum)
                .sort('Items sold sum', descending=True)
                .column('Product')
                .item(0) )


'C'

# 6 a choice 1 (incorrect)
This groups but never sorts by the totals.  `.item(0)` just returns the first row in grouped order, not the max.

In [26]:
(humboldt_sales.group('Product', sum)
 .column('Product')
 .item(0))


'A'

# 6 a choice 2 (incorrect)
Sorting before grouping is irrelevant, because grouping will discard the row order.  So `item.(0)` is not guaranteed to be the maximum.

In [27]:
(humboldt_sales.sort('Items sold', descending=True)
 .select('Product', 'Items sold')
 .group('Product', sum)
 .column('Product')
 .item(0))


'A'

# 6 a choice 4 (incorrect)
Sorts ascending, so it returns the least popular product.

In [28]:
(humboldt_sales.select('Product', 'Items sold')
 .group('Product', sum)
 .sort('Items sold sum')
 .column('Product')
 .item(0))


'B'

# 6 b choice 2

In [29]:
# since we need total sales for each product in each city, we need info from both tables and will have to use a join
( humboldt_sales.join('Customer_ID', humboldt_customers)
               .pivot('Product', 'City', 'Sale amount ($)', sum) )


City,A,B,C
Arcata,100,380,160
Eureka,200,0,290
Trinidad,120,220,0


In [30]:
# choice 1
(humboldt_sales.join('Customer_ID', humboldt_customers)
        .pivot('Product', 'City', 'Sale amount ($)', sum) ) # product across top, city down left


City,A,B,C
Arcata,100,380,160
Eureka,200,0,290
Trinidad,120,220,0


In [31]:
# choice 2 
( humboldt_sales.join('Customer_ID', humboldt_customers)
        .pivot('City', 'Product', 'Sale amount ($)', sum) ) # city across top as requested

Product,Arcata,Eureka,Trinidad
A,100,200,120
B,380,0,220
C,160,290,0


# 6 c choice is 1
- joins tables
- groups by customer name and sums their `Items sold`
- sorts ascending and picks first
Gives customer with the fewest total items sold.

In [32]:
( humboldt_sales.join('Customer_ID', humboldt_customers)
               .group('Customer_Name', sum)
               .sort('Items sold sum')  # ascending → fewest first
               .column('Customer_Name')
               .item(0) )


'Alice'

# 6 c choice 2 (incorrect)
Just returns the first row's items, not a per customer total, and not a name.

In [33]:
(humboldt_sales.join('Customer_ID', humboldt_customers)
 .column('Items sold').item(0))


10

# 6 c choice 3 (incorrect)
Uses the minimum of `Items sold` per customer (customer's smallest single purchase), not the total across purchases.

- joins table
- groups by customer name and gives the minimum of `Items sold` (smallest purchase for each customer)
- takes first item

In [34]:
(humboldt_sales.join('Customer_ID', humboldt_customers)
 .group('Customer_Name', min)
 .column('Customer_Name').item(0))


'Alice'

# 7 a

In [35]:
colors = Table().with_columns(
    'color',  make_array('BLUE','GREEN','RED','YELLOW'),
    'number', make_array(6, 7, 4, 3)
)
colors

color,number
BLUE,6
GREEN,7
RED,4
YELLOW,3


# 7 b

In [42]:
def chance_of_marbles(color1, color2):
    total_marbles = sum(colors.column('number'))
    num_color1 = colors.where('color', color1).column('number').item(0)
    num_color2 = colors.where('color', color2).column('number').item(0)
    if color1 == color2:
        chance = (num_color1 * (num_color1 - 1)) / (total_marbles * (total_marbles - 1))
    else:
        chance = (num_color1 * num_color2) / (total_marbles * (total_marbles - 1))
    return chance


In [43]:
chance_of_marbles('BLUE',"GREEN")

0.11052631578947368

In [39]:
num_color1 = colors.where('color', 'RED').column('number')#.item(0)
num_color1

array([4])

# 8

In [23]:
toppings = Table().with_columns(
    'Topping', make_array('olive','pepper','tomato'),
    'Count',   make_array(85, 72, 74)
)
toppings

Topping,Count
olive,85
pepper,72
tomato,74


# 8 a
- NH: The chance of a topping being a tomato is 1/3.
- AH: The chance of a topping being a tomato is fewer than 1/3.

# 8 b
the count or the proportion of tomatoes are both good choices for a test statistic (so the first 2 options)

# 8 c
There are 74 tomatoes out of a total of 231 toppings, so 74/231

In [24]:
74/231

0.3203463203463203

# 8 d

In [25]:
predicted = make_array(1/3, 1/3, 1/3) # null
samp_size = sum(toppings.column("Count"))

def one_simulated_statistic():
    num_tomatoes = sample_proportions(samp_size, predicted).item(2)  
    return num_tomatoes


# 8 e

In [26]:
sim_stats = make_array()
for i in np.arange(10000):
    sim_stats = np.append(sim_stats, one_simulated_statistic())


# 8 f

In [27]:
empirical_pval = np.count_nonzero(sim_stats <= observed_statistic) / 10000
empirical_pval

NameError: name 'observed_statistic' is not defined

# 8 g
We do not (fail to) reject the null hypothesis.

# 8 h
- NH: Toppings are distributed according to the probability distribution specified by the professor.
- AH: Toppings are not distributed according to the professor’s distribution.

# 8 i

In [78]:
def tvd(pred, obs):
    return 0.5 * sum(np.abs(pred - obs))

predicted = make_array(1/3, 1/3, 1/3)
samp_size = sum(toppings.column('Count'))
observed = make_array(85, 72, 74) / samp_size
observed_tvd = tvd(predicted, observed)
observed_tvd

0.034632034632034625